---
- name: Create Users, Groups with permissions
  hosts: all
  vars_files: 
    - users.yml
  become: true

  tasks:
    - name: Create groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      with_items:
        - "admin"
        - "developer"
    - name: Allow passwordless sudo in admin group
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ item }}'
        line: '%{{ item }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      with_items: 
        - "admin"
    - name: Allow access to /var/log/ to developer group
      ansible.builtin.file:
        path: /var/log/
        group: "{{ item }}"
        state: directory
        recurse: yes
        mode: '0754'
      with_items: 
        - "developer"
    - name: Create Users from users.yml
      ansible.builtin.user:
        name: "{{ item['name'] }}"
        shell: /bin/bash
        groups: "{{ item['role'] }}"
        append: yes
        state: present
      with_items: "{{ users }}"  
    - name: Add Authorized keys
      ansible.posix.authorized_key:
        user: "{{ item['name'] }}"
        state: present
        key: "{{ lookup('file', item['key']) }}"
      with_items: "{{ users }}"  
      when: "item['key-present'] == True"
    - name: Add Authorized keys from GitHub url
      ansible.posix.authorized_key:
        user: "{{ item['name'] }}"
        state: present
        key: https://github.com/{{item['name']}}.keys
      with_items: "{{ users }}"  
      when: "item['key-present'] == False"
    